config/routes.rb
Rails.application.routes.draw do
  get 'tags/:tag', to: 'farms#index', as: :tag
  resources :farms
  resources :merchants

  root 'welcome#index'

end

app/models/farm.rb
class Farm < ActiveRecord::Base
	validates :name, :presence => true
	acts_as_taggable
  # acts_as_taggable_on
	geocoded_by :address
	after_validation :geocode, if: :address_changed?
	has_and_belongs_to_many :merchants
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
	validates :name, :presence => true
	acts_as_taggable
	geocoded_by :address
	after_validation :geocode, if: :address_changed?
	has_and_belongs_to_many :farms
end

app/models/merchantfarm.rb
class merchants_farms < ActiveRecord::Base
	belongs_to :farm
	belongs_to :merchant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
	before_filter :tag_names, only: [:new, :edit]
	before_filter :merchant_list, only: [:new, :edit]

	def index
		if params[:search]
			@farms = Farm.tagged_with(params[:search], :wild => true, :any => true)
		elsif params[:tag]
			@farms = Farm.tagged_with(params[:tag]).order(name: :asc)
			@tag = params[:tag]
		else
			@farms = Farm.all.order(name: :asc)
		end

		respond_to do |format|
			format.html
			format.js
			format.json{ render json: @farms}    
		end
	end

	def new
		@farm = Farm.new
	end

	def create
		@farm = Farm.new(farm_params)
		puts "My Farm is currently #{@farm.inspect}"
		if @farm.save
			redirect_to @farm
		else 
			render 'new'
		end
	end

	def show 
		@farm = Farm.find(params[:id])
	end

	def destroy
	end

	def edit
		@farm = Farm.find(params[:id])
	end

	def update
		@farm = Farm.find(params[:id])

		if @farm.update_attributes(farm_params)
			redirect_to @farm
		else
			render :edit
		end
	end

	private
	def farm_params
		params.require(:farm).permit(:tag_list, :name, :address, :description, :phone_number, :website, :vendor_list)
	end

	def tag_names
		@tag_names = Farm.tag_counts.inject([]) do |array, tag| array.push(tag.name); array end
	end

	def merchant_list
		@merchant_names = Merchant.all.map do |merchant| {id: merchant.id, text: merchant.name}
		end
	end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
	before_filter :tag_names, only: [:new, :edit]
	
	def index
		@merchants = Merchant.all

		respond_to do |format|
			format.html {}
			format.js {}
		end
	end

	def new
		@farms = Farm.all
		@merchant = Merchant.new
	end

	def create
		@merchant = Merchant.new(merchant_params)
		farm_ids = params[:merchant][:farm_ids]
		@merchant.farm_ids = farm_ids
		if @merchant.save
			redirect_to @merchant
		else 
			render 'new'
		end
	end

	def show 
		@merchant = Merchant.find(params[:id])
	end

	def destroy
	end

	def edit
		@merchant = Merchant.find(params[:id])
	end

	def update
		@merchant = Merchant.find(params[:id])
		if @merchant.update_attributes(merchant_params)
			redirect_to merchant_path(@merchant)
		else
			render :edit
		end
	end

	def destroy
		@merchant = Merchant.find(params[:id])
		@merchant.destroy
		redirect_to merchants_path
	end
	
	private
	def merchant_params
		params.require(:merchant).permit(:name, :address, :description, :phone_number, :website, :tag_list, :farm_ids => [])
	end

	def tag_names
		@tag_names = Farm.tag_counts.inject([]) do |array, tag| array.push(tag.name); array end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
    @tags = Farm.tag_counts_on(:tags, order: "count desc") 
	end

	def all

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/farms/_farm.html.erb
<%= link_to farm_path(farm.id) do %>
  <h5>
    <%= link_to farm.name, farm %><br/>
    <% if farm.description %>
		  <%= farm.description %> <br/>
    <% end%>
		<%= farm.address %>
  </h5>
<% end %>

app/views/farms/_form.html.erb
<%= form_for @farm do |f| %>
  <div class="row">
    <div class="small-9 columns">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row">
    <div class="small-9 columns">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>
  </div>
  <div class="row">
    <div class="small-9 columns">
      <%= f.label :phone_number %><br>
      <%= f.text_field :phone_number %>
    </div>
  </div>
  <div class="row">
    <div class="small-9 columns">
      <div class="projectinfo">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>
    </div>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :tags_list, "Available Products"  %><br />
    <%= f.text_area :tag_list %>
  </div>
  <br>

  <dv class="field">
    <%= f.label :vendor_list %><br>
    <%= f.text_area :vendor_list %>
  </div>
  <br>
  <br>
  <div class="action">
    <%= f.submit class: "button medium left" %>
  </div>
<% end %>

<%= javascript_tag do%>
  var tag_names = <%= raw tag_names %>;
  var merchant_names = <%= raw merchant_names.to_json %>;
<% end %>

app/views/farms/edit.html.erb
<div class="container">
	<h1>Edit Your Farm</h1>
	<br>
	<div class="links"><%= link_to "Back", @farm %></div>

	<%= render partial: "form", locals:{tag_names: @tag_names, merchant_names: @merchant_names} %>
</div>

app/views/farms/index.html.erb
<div class="container">
	<div class="container">
    <h1> Farms </h1> 
    <%= link_to "Post a new Farm", new_farm_path %>
    <br />
    <br />
    <% if params[:tag] %>
      <p class="grown-here">Farms that grow <%= @tag %> </p>
    <% end %>

    <div id="farm-index"></div>
    <div id="map-container">
      <div id="map-canvas"></div>
    </div>
    <div id="geo-locate"></div>
    <br />
    <div id="farms">
      <%= render @farms %>
    </div>
    <script type="text/javascript">
      farms_coords = <%= raw @farms.map { |f| { latitude: f.latitude.to_f, longitude: f.longitude.to_f, infoWindow: (render partial: "info_window", locals: {farm: f})}}.to_json %>
    </script>
  </div>
</div>

app/views/farms/index.js.erb
farms_coords = <%= raw @farms.map { |f| { latitude: f.latitude.to_f, longitude: f.longitude.to_f, infoWindow: (render partial: "info_window", locals: {farm: f})}}.to_json %>
	
map.setCenter(new google.maps.LatLng(<%= params[:latitude]%> , <%= params[:longitude]%>));
map.setZoom(10);
addMarkers(farms_coords, 0);

app/views/farms/new.html.erb
<div class="container">
  <div class="container">
  	<h1>Add a Farm</h1>
  	<div class="links"><%= link_to "Back", @farm %></div>
  	<br>
  	<%= render partial: "form", locals: {tag_names: @tag_names, merchant_names: @merchant_names} %>
  </div>
</div>

app/views/farms/show.html.erb
<div class="container">
	<div class="container">
	<div class="row">
	  <div class="large-12 columns">
	  	<h1> <%= @farm.name %></h1>
	  	<h2> <%= @farm.address %> </h2>
	  </div>
	</div>


	<div class="row">
	  <div class="large-7 columns">
	  	<div id="map-canvas"></div>
	  </div>

	  <div class="large-5 columns">
	  	<div class="panel">
	  		<h4> About us: </h4>
		  	<p> <%= @farm.description %> </p>
		  	<% if !@farm.website.nil? %>
		  		<%= link_to @farm.website, @farm.website, target: "_blank" %><br>
				<% end %>
		  	<%= link_to "Edit Farm", edit_farm_path(@farm) %>|
				<%= link_to "Delete Farm", @farm, :confirm => "Are you sure you want to delete?", :method => :delete %>
				
				<%= javascript_tag do %>
				window.farmLat = <%= @farm.latitude %>;
				window.farmLong = <%= @farm.longitude %>;
				window.coords = <%= raw [{latitude: @farm.latitude, longitude: @farm.longitude}].to_json %>
				<% end %>
				<div id="show-page"></div>
			</div>
		  
	  </div>
	</div>

	<div class="row">
	  <div class="large-12 columns">
			<div class= "panel callout">
	  		<p> Foods grown here: <%= raw @farm.tag_list.map { |t| link_to t, tag_path(u(t)) }.join(', ')%></p>
	  	</div>
	  </div>
	</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<title><%= content_for?(:title) ? yield(:title) : "Localvore" %></title>

	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "vendor/modernizr" %>
	<%= csrf_meta_tags %>


	<link href='http://fonts.googleapis.com/css?family=Muli:300' rel='stylesheet' type='text/css'>

	<%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?libraries=geometry&key=#{Figaro.env.google_maps_api}&sensor=false" %>

    
</head>

<body>
		<div class="navbar">
			<div class="navbuttons">
					<div class="navbutt">
						<div class="navsearch">
							<%= form_tag farms_path, method: :get, authentication: false, id: 'search-form' do %>
							<%= text_field_tag :search, params[:search], placeholder: "Search by product..." %>
							
							<% end %>
						</div>

					</div>
					<div class="navbutt"><%= link_to "Farms", farms_url %></div>
					<div class="navbutt"><%= link_to "Merchants", merchants_url %></div>
			</div>
			<h3><%= link_to "Localvore", root_path %></h3>
		</div>
	</div>
		

	
				<%= yield %>

		
		<%= javascript_include_tag 'application' %>
	</body>
	</html>

	<%= javascript_tag do %>
	 window.icons = [
			"<%= image_url 'farm_marker.png' %>",
			"<%= image_url 'merch_marker.png' %>"
			];
			<% end %>

app/views/merchants/_form.html.erb
<%= form_for @merchant do |f| %>
  <div class="row">
    <div class="small-9 columns">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row">
    <div class="small-9 columns">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>
  </div>
  <div class="row">
    <div class="small-9 columns">
      <%= f.label :phone_number %><br>
      <%= f.text_field :phone_number %>
    </div>
  </div>
  <div class="row">
    <div class="small-9 columns">
      <div class="projectinfo">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>
    </div>
  </div>

   <!--  <div class="field">
    <%= f.label :tags_list, "Available Products"  %><br />
    <%= f.text_area :tag_list %>
  </div> -->
  <br>

  <div class="row">
    <div class="small-9 columns">
      <div class="projectinfo">
        <%= f.label :farm_ids, "Sources" %><br>
        <%= f.select :farm_ids, options_from_collection_for_select(@farms, :id, :name),{}, { multiple: true, style:"width: 500px;" } %>
      </div>
    </div>
  </div>
    <br>
    <%= f.submit class: "button medium left" %>
  </div>

<% end %>

<%= javascript_tag do %>
  var tag_names = <%= raw tag_names %>;
<% end %>

app/views/merchants/_info_window.html.erb
<h6><%= link_to merchant.name, merchant %></h6>
<h7><%= merchant.address %> </h7>

app/views/merchants/_merchant.html.erb
<%= link_to merchant_path(merchant.id) do %>
  <h5>
    <%= link_to merchant.name, merchant %>
    <% if merchant.description %>
		  <%= merchant.description %> <br/>
    <% end%>
		<%= merchant.address %> <br />
  </h5>
<% end %>

app/views/merchants/edit.html.erb
<div class="container">
	<h1>Edit Merchant</h1>

	<%= render partial: 'form', locals: {farm_names: @farm_names, tag_names: @tag_names} %>
</div>

app/views/merchants/index.html.erb
<div class="container">
	<div class="container">
	<h1> Merchants </h1>
	<%= link_to "Post a new Merchant", new_merchant_path %>
	<br>
	<p> To view more information about a merchant and find out where the food they sell comes from, click on a yellow marker andfollow the link inside.</p>

	<div id="merch-index"></div>
	
	<div id="map-container">
	  <div id="map-canvas"></div>
	</div>
	<div id="geo-locate"></div>

	 <%= render @merchants %>


	<script type="text/javascript">
	  merch_coords = <%= raw @merchants.map { |f| { latitude: f.latitude.to_f, longitude: f.longitude.to_f, infoWindow: (render partial: "info_window", locals: {merchant: f})}}.to_json %>
	</script>
</div>
</div>

app/views/merchants/index.js.erb
merchants_coords = <%= raw @merchants.map { |m| { latitude: m.latitude.to_f, longitude: m.longitude.to_f, infoWindow: (render partial: "info_window", locals: {merchant: m}) }}.to_json %>

addMarkers(merchants_coords, 1);

app/views/merchants/new.html.erb
<div class="container">
  <div class="container">
  	<h1> Add a Merchant </h1> 

  	<%= render partial: 'form', locals: {farm_names: @farm_names, tag_names: @tag_names} %>
  </div>
</div>

app/views/merchants/show.html.erb
<div class="container">
  <div class="container">
    <div class="row">
      <div class="large-12 columns">
      	<h1> <%= @merchant.name %></h1>
      	<h2> <%= @merchant.address %> </h2>
        <p> This map shows the farms where <%= @merchant.name %> buys their food! The map also includes a 100 km radius to give you an idea about how far your food has travelled. </p>
      </div>
    </div>


    <div class="row">
      <div class="large-7 columns">
      	<div id="map-canvas"></div>
      </div>

      <div class="large-5 columns">
      	<div class="panel">
      		<h4> About us: </h4>
          <p> <%= @merchant.description %> </p>
          <%= link_to "Edit Merchant", edit_merchant_path(@merchant) %>|
          <%= link_to "Delete Merchant", @merchant, :confirm => "Are you sure you want to delete?", :method => :delete %>
          <div id="show-page"></div>
          <div id="merch-show"></div>		
          <%= javascript_tag do %>
          window.farmLat = <%= @merchant.latitude %>;
          window.farmLong = <%= @merchant.longitude %>;
          window.polyCoords = <%= raw @merchant.farms.map { |r| { latitude: r.latitude.to_f,longitude: r.longitude.to_f, infoWindow: (render partial: "info_window", locals: {merchant: r})}}.to_json %>
          <% end %>

        </div>

      </div>
    </div>

<!--     <div class="row">
      <div class="large-12 columns">
    		<div class= "panel callout">
      		<p> Locally grown foods sold here: <%= raw @merchant.tag_list.map { |t| link_to t, tag_path(u(t)) }.join(', ')%></p>
      	</div>
      </div>
    </div> -->
  </div>
</div>

app/views/welcome/_info_window.html.erb
<h6><%= link_to farm.name, farm %></h6>
<h7><%= farm.address %> </h7>

app/views/welcome/index.html.erb
<div class="farm-img" style="background-image: url('<%= image_path "farm_field.jpeg" %>')">
  <div class="image_filter"></div>
  <div class="image_text">Eating locally made easy.</div>
  <%= link_to farms_url do %>
    <div class="farms_button">Discover farms near you</div>
  <%end%>
  <%= link_to merchants_url do %>
    <div class="merchs_button">Learn more about local merchants</div>
  <%end%>
</div>


<div class="container">
  <div class="row">
    <div class="large-12 columns">
      <h4 class= "text-center"> The local food movement is a collaborative effort to build more locally based, self-reliant food economies - one in which sustainable food production, processing, distribution, and consumption is integrated to enhance the economic, environmental and social health of a community. Localvore is dedicated to connecting users with locally grown food by allowing merchants and restaurants to disclose farms they purchase goods from.  </h4>
    </div>  
  </div>
  </div>  


  <div class="container">
  <div class="row">
    <div class="large-12 columns">
      <h2 class="text-center"> Farms & Markets near you </h2>
      <div id="map-canvas"></div>
      <div class="slideTwo">
        <input type="checkbox" id="farms-checkbox" name="check" checked>
        <label for="farms-checkbox"></label>
        <p>Farms</p>
      </div>
      <div class="slideTwo">
        <input type="checkbox" id="merchants-checkbox">
        <label for="merchants-checkbox"></label>
        <p>Merchants</p><br />
      </div>
      <div id="farm-index"></div>
      <div id="geo-locate"></div>
    </div>
  </div>
  </div>

  <script type="text/javascript">
    farms_coords = <%= raw @farms.map { |f| { latitude: f.latitude.to_f, longitude: f.longitude.to_f, infoWindow: (render partial: "info_window", locals: {farm: f})}}.to_json %>
    merch_coords = <%= raw @merchants.map { |m| { latitude: m.latitude.to_f, longitude: m.longitude.to_f, infoWindow: (render partial: "info_window", locals: {farm: m}) }}.to_json %>
  </script>

</div>